### ISSUE TITLE
Failure [INSTALL_PARSE_FAILED_MANIFEST_MALFORMED]

### ISSUE THREAD

**Issue by fraylopez** [BranchMetrics/Branch-AIR-ANE-SDK#1]
Hi

Thanks for your work! first issue! ;-)

Using your demo app.xml I get the manifest malformed error.
If I comment the activity which is supposed to launch my app from url scheme i can compile again.

Comment this:

	<activity android:excludeFromRecents="false">
		<intent-filter>
			<action android:name="android.intent.action.VIEW" />
			<data android:scheme="appName"/>
			<category android:name="android.intent.category.DEFAULT" />
			<category android:name="android.intent.category.BROWSABLE" /> 
		</intent-filter> 
	</activity>

**Comment by alamboley** [comment]
Hey,

Do you have any other ANEs with your project? The app.xml shouldn't have malformed issue.

**Comment by fraylopez** [comment]
Yep, I have a lot of anes but until now everithing was working

**Comment by alamboley** [comment]
Could you post your whole app.xml ?
Thanks.

**Comment by fraylopez** [comment]
Hi,
I remove the other ANEs but I still got the error. Here's my app.xml. Thanks!


    <manifestAdditions><![CDATA[
		<manifest android:installLocation="auto">
			<uses-sdk android:minSdkVersion="8" />
			<uses-permission android:name="android.permission.INTERNET" />
			
			<application android:enabled = "true" android:hardwareAccelerated="true">
				
					
					
						
					<meta-data android:name="io.branch.sdk.BranchKey" android:value="key_live_XXXXXXXXXXXXXXXXXXX" />
					<activity android:name="io.branch.nativeExtensions.branch.BranchActivity" 
						android:launchMode="singleTask" 
						android:theme="@android:style/Theme.Translucent.NoTitleBar.Fullscreen" />

					<activity android:excludeFromRecents="false">
						<intent-filter>
							<action android:name="android.intent.action.VIEW" />
							<data android:scheme="zink"/>
							<category android:name="android.intent.category.DEFAULT" />
							<category android:name="android.intent.category.BROWSABLE" /> 
						</intent-filter> 
					</activity>
					
			</application>	

		</manifest>
	]]>
	</manifestAdditions>
  </android>
  <extensions>

		<extensionID>io.branch.nativeExtensions.Branch</extensionID>
		
  </extensions>

**Comment by alamboley** [comment]
Hey, I don't know what is your issue with your *-app.xml but it doesn't work on my side too. I think it's because you didn't provide an intent-filter for MAIN and LAUNCHER.

I've removed unnecessary args from the *-app.xml. I invite you to try again, and respect elements order.

**Comment by fraylopez** [comment]
Good morning! Still no luck...
I added the intent-filters you mentioned and removed the excludeFromRecents property. Any ideas?


This is what I have now:

    <manifestAdditions><![CDATA[
		<manifest android:installLocation="auto">
			<uses-sdk android:minSdkVersion="8" />
			<uses-permission android:name="android.permission.INTERNET" />

<application android:enabled = "true" android:hardwareAccelerated="true">
			
					<meta-data android:name="io.branch.sdk.BranchKey" android:value="key_live_xxxxxxxxxxxxxxxxxxxxxxxxx" />
					<activity>
						 <intent-filter>
							<action android:name="android.intent.action.MAIN"/>
							<category android:name="android.intent.category.LAUNCHER"/>
						</intent-filter>
						 <intent-filter>
							<action android:name="android.intent.action.VIEW" />
							<data android:scheme="zink"/>
							<category android:name="android.intent.category.DEFAULT" />
							<category android:name="android.intent.category.BROWSABLE" /> 
						</intent-filter> 
					</activity>
					<activity android:name="io.branch.nativeExtensions.branch.BranchActivity" android:launchMode="singleTask" android:theme="@android:style/Theme.Translucent.NoTitleBar.Fullscreen" />
					
			</application>	

		</manifest>
	]]>
	</manifestAdditions>



	<extensionID>io.branch.nativeExtensions.Branch</extensionID>

</application>

**Comment by fraylopez** [comment]
Hi again!

It seem to work for me if I add a dummy "package-like" name atribute to the activity...
I wish I could help you more, still learning 

This is what I have
```
    <manifestAdditions><![CDATA[
		<manifest android:installLocation="auto">
			<uses-sdk android:minSdkVersion="8" />
			<uses-permission android:name="android.permission.INTERNET" /> 
            <application android:enabled = "true" android:hardwareAccelerated="true">
			
					<meta-data android:name="io.branch.sdk.BranchKey" android:value="key_live_xxxxxxxxxxxxxxxxxxxxxxxxx" />
					<activity android:name="dummy.package.name">
						 <intent-filter>
							<action android:name="android.intent.action.MAIN"/>
							<category android:name="android.intent.category.LAUNCHER"/>
						</intent-filter>
						 <intent-filter>
							<data android:scheme="zink"/>
							<action android:name="android.intent.action.VIEW" />
							<category android:name="android.intent.category.DEFAULT" />
							<category android:name="android.intent.category.BROWSABLE" /> 
						</intent-filter> 
					</activity>
					<activity android:name="io.branch.nativeExtensions.branch.BranchActivity" android:launchMode="singleTask" android:theme="@android:style/Theme.Translucent.NoTitleBar.Fullscreen" />
					
			</application>	

		</manifest>
	]]>
	</manifestAdditions>

```
...
```
<extensionID>io.branch.nativeExtensions.Branch</extensionID>
```

**Comment by alamboley** [comment]
Hmm ok. On which IDE are you compiling? What is your AIR version?

**Comment by fraylopez** [comment]
I'm developing an Android/iOs App using FlashDevelop with AIR 16.0.
I can compile now,  but so far with no luck launching the app from a link using the scheme name on Android. Everithing ok in iOS

**Comment by alamboley** [comment]
For my test app, I put `branch-ane-test://` for the Android URI Scheme.
Do you have this problem on a small sample project or a big one with many ANEs?

**Comment by fraylopez** [comment]
I'm using a modified version of my project loading only the Branch ANE. 
I've been doing some more testing and things are getting bizarre...

First I got a new manifest error about the dummy name being overriten (which isn't such a surprise after all) so I removed it leaving just the <activity> tag as you said before.

Then I've found that the link is launching my app just in some of my testing devices:
(The link should open the app if present or the store if not.)

iPhone 7 IOS 7.1.2 : OK
iPhone 8 IOS 8.3 : OK
NexusS Android 4.2.2 Cyanogen 10.1 : OK

Acer Iconia A1 Android 4.4.2 Stock : FAIL, open store
Nexus 4 Android 5.1 Stock : FAIL, open store

 Unbranded Chinese Tablet Andoid 4.2.2 Stock? : FAIL, open store

**Comment by alamboley** [comment]
Hmm that strange, it works fine on my Nexus 7 with Android 5.1

Things related to just opening the app from a link is not really related to Branch. AIR SDK does it directly. On the device with the issue, could you try to:
- remove the branch stuff from the *-app.xml.
- create an other app with a simple button calling: `navigateToURL(new URLRequest("branch-ane-test:"));`

It should open your app. Be careful, the `:` matter.

**Comment by fraylopez** [comment]
Yep, it works calling the navigateToURL with  scheme name and the ```:```

appname:
appname://

they both work

**Comment by alamboley** [comment]
Ok, did you change the app.xml ? From your previous test? If, yes could you try to navigate to your app via the Branch link? Again, you didn't the branch ANE stuff to do that.
Maybe that's an issue with the browser on those devices.

**Comment by fraylopez** [comment]
Actually I made a dummy html page with all the links, instead of a new launcher app to save time.
I put the Branch link as well as the ```appname: ``` links to test.
Only the Branch link isn't launching the app using Chrome.

I'm going to try with another browser

**Comment by alamboley** [comment]
Ok, yep that might be the issue. I don't know how the other browser manage that stuff.

**Comment by fraylopez** [comment]
You were right! Firefox launches the app. WTF!

**Comment by alamboley** [comment]
You mean Firefox *doesn't* launch the app?

**Comment by fraylopez** [comment]
Sorry, I mean that everithing is fine with Firefox, it launches the app from the Branch link as is suposed to.

**Comment by alamboley** [comment]
Ok, could you sum up your test & settings please? I want to be sure to located the issue.

**Comment by fraylopez** [comment]
I'll try to summarize...

The Branch link seems to fail only in Chrome (Firefox and old default android Browser do work )

The manifest malformed error seems to be caused by a conflict with another ane (AdColony?) intent-filters. I added the activity name pointing to ```air.my.package.AppEntry``` and now everything seems to coexist together. 

These are the two blocks:
```
<!-- AdColony -->
				
					<activity android:launchMode="singleTop">
						<intent-filter>
						  <action android:name="android.intent.action.MAIN"/>
						  <category android:name="android.intent.category.LAUNCHER"/>
						</intent-filter>
					</activity>
					<activity android:name="com.jirbo.adcolony.AdColonyOverlay" android:windowSoftInputMode="adjustNothing" android:configChanges="keyboardHidden|orientation|screenSize" android:theme="@android:style/Theme.Translucent.NoTitleBar.Fullscreen" />
					<activity android:name="com.jirbo.adcolony.AdColonyFullscreen" android:configChanges="keyboardHidden|orientation|screenSize" android:theme="@android:style/Theme.Black.NoTitleBar.Fullscreen" />
					<activity android:name="com.jirbo.adcolony.AdColonyBrowser" android:configChanges="keyboardHidden|orientation|screenSize" android:theme="@android:style/Theme.Black.NoTitleBar.Fullscreen" />

```
```
	<!-- Branch -->
						
					<meta-data android:name="io.branch.sdk.BranchKey" android:value="key_live_XXXXXXXXXx />
					<activity android:name="air.my.package.AppEntry" android:theme="@android:style/Theme.Translucent.NoTitleBar.Fullscreen" >
						 <intent-filter>
							<action android:name="android.intent.action.MAIN"/>
							<category android:name="android.intent.category.LAUNCHER"/>
						</intent-filter>
						<intent-filter>
							<data android:scheme="zink"/>
							<action android:name="android.intent.action.VIEW" />
							<category android:name="android.intent.category.DEFAULT" />
							<category android:name="android.intent.category.BROWSABLE" />
						</intent-filter>
					</activity> 
					<activity android:name="io.branch.nativeExtensions.branch.BranchActivity" android:launchMode="singleTask" android:theme="@android:style/Theme.Translucent.NoTitleBar.Fullscreen" />

```

**Comment by alamboley** [comment]
You could merge them like this:
```xml
<meta-data android:name="io.branch.sdk.BranchKey" android:value="key_live_XXXXXXXXXx />
  <activity android:launchMode="singleTop">
                        <intent-filter>
                          <action android:name="android.intent.action.MAIN"/>
                          <category android:name="android.intent.category.LAUNCHER"/>
                        </intent-filter>
                       <intent-filter>
                            <data android:scheme="zink"/>
                            <action android:name="android.intent.action.VIEW" />
                            <category android:name="android.intent.category.DEFAULT" />
                            <category android:name="android.intent.category.BROWSABLE" />
                        </intent-filter>
                    </activity>
                    <activity android:name="com.jirbo.adcolony.AdColonyOverlay" android:windowSoftInputMode="adjustNothing" android:configChanges="keyboardHidden|orientation|screenSize" android:theme="@android:style/Theme.Translucent.NoTitleBar.Fullscreen" />
                    <activity android:name="com.jirbo.adcolony.AdColonyFullscreen" android:configChanges="keyboardHidden|orientation|screenSize" android:theme="@android:style/Theme.Black.NoTitleBar.Fullscreen" />
                    <activity android:name="com.jirbo.adcolony.AdColonyBrowser" android:configChanges="keyboardHidden|orientation|screenSize" android:theme="@android:style/Theme.Black.NoTitleBar.Fullscreen" />
<activity android:name="io.branch.nativeExtensions.branch.BranchActivity" android:launchMode="singleTask" android:theme="@android:style/Theme.Translucent.NoTitleBar.Fullscreen" />
```

**Comment by fraylopez** [comment]
Thank you! the merge worked.

The chrome issue seems to be well known, I found this in the android SDK integration guide:
https://github.com/BranchMetrics/Branch-Android-SDK#register-an-activity-for-direct-deep-linking-optional-but-recommended
 
```
<data android:scheme="zink" android:host="open" />
```

**Comment by alamboley** [comment]
I tried adding the `android:host="open"` but it seems that AIR doesn't like it. Maybe you will have more luck?

**Comment by fraylopez** [comment]
Nop it didn't work for me either...
I'll post if I found a workaround

**Comment by alamboley** [comment]
Ok thanks. For the moment I'll close the issue, since it doesn't sound related to the ANE at all.
